[package]
name = "mqtt-proto"
version = "0.2.0"
license = "MIT"
description = "MQTT v3.1/v3.1.1/v5.0 protocol sync/async codec."
authors = ["LinFeng <thewawar@gmail.com>"]
repository = "https://github.com/akasamq/mqtt-proto"
readme = "README.md"
keywords = ["mqtt", "codec", "network", "async"]
categories = ["network-programming", "asynchronous"]
edition = "2021"

[dependencies]
bytes = { version = "1", default-features = false }
embedded-io = { version = "0.6", default-features = false }
embedded-io-adapters = { version = "0.6", features = ["std", "tokio-1"], optional = true }
embedded-io-async = { version = "0.6", default-features = false }
thiserror = { version = "2", default-features = false }
simdutf8 = { version = "0.1", default-features = false }

# Future impls
embassy-futures = { version = "0.1" }
futures-lite = { version = "2", optional = true }

# Only for fuzz testing
arbitrary = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
proptest = "1.0.0"
tokio = { version = "1", features = ["full"] }

[features]
default = ["std"]
std = ["dep:embedded-io-adapters", "dep:futures-lite", "thiserror/std"]
