name: Benchmark Codec

on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:

jobs:
  benchmark:
    name: Run benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        run: |
          rustup toolchain install nightly
          rustup default nightly

      - name: Run memory test
        run: |
          set -o pipefail

          # Create temporary file
          temp_file=$(mktemp)

          # Run test and capture output
          cargo test --features dhat-heap -- --nocapture --test-threads 1 | tee "$temp_file"

          # Process output
          echo "## Memory Test Results" >> $GITHUB_STEP_SUMMARY
          echo "| Test | Start Bytes | End Bytes | Peak Bytes | Peak Blocks | Throughput (Mbps) | Jobs/sec | Avg Time/job (us) |" >> $GITHUB_STEP_SUMMARY
          echo "|------|-------------|-----------|------------|-------------|-------------------|----------|-------------------|" >> $GITHUB_STEP_SUMMARY

          grep '^{.*"test":' "$temp_file" | while read -r line; do
            echo "$line" | jq -e -r '[.test, .bytes[0], .bytes[1], .peak_bytes, .peak_blocks, .throughput_mbps, .jobs_per_sec, .avg_time_per_job_us] | @tsv' 2>/dev/null
          done | while IFS=$'\t' read -r test start end peak_bytes peak_blocks throughput jobs_per_sec avg_time; do
            echo "| $test | $start | $end | $peak_bytes | $peak_blocks | $throughput | $jobs_per_sec | $avg_time |" >> $GITHUB_STEP_SUMMARY
          done

          # Clean up temporary file
          rm -f "$temp_file"

      - name: Run benchmark
        run: |
          set -o pipefail

          # Create temporary file
          temp_file=$(mktemp)

          # Run test and capture output
          cargo bench | tee "$temp_file"

          # Process output
          echo "## Benchmark Results" >> $GITHUB_STEP_SUMMARY
          echo "| Name | Time (ns/iter) | Stddev |" >> $GITHUB_STEP_SUMMARY
          echo "|------|----------------|--------|" >> $GITHUB_STEP_SUMMARY

          grep "bench:" "$temp_file" | sed -E 's/test ([^ ]+) \.\.\. bench: *([0-9,.]+) ns\/iter \(\+\/- ([0-9,.]+)\)/| \1 | \2 | \3 |/' \
          >> $GITHUB_STEP_SUMMARY

          # Clean up temporary file
          rm -f "$temp_file"
