name: Benchmark Codec

on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:

jobs:
  benchmark:
    name: Run benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        run: |
          rustup toolchain install nightly
          rustup default nightly

      - name: Run memory test
        run: cargo test --features dhat-heap -- --nocapture --test-threads 1

      - name: Run benchmark
        run: cargo bench | tee output.txt

      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Rust Benchmark Results
          tool: 'cargo'
          output-file-path: output.txt
          external-data-json-path: ./cache/benchmark-data.json
          fail-on-alert: true
          summary-always: true
